#undef NETSTACK_CONF_RADIO
#define NETSTACK_CONF_RADIO cc2420_driver
#undef NETSTACK_CONF_FRAMER
#define NETSTACK_CONF_FRAMER framer_802154
#undef NETSTACK_CONF_MAC
#define NETSTACK_CONF_MAC  csma_driver
